### ISSUE TITLE
https-only compatibility broken

### ISSUE THREAD

**Issue by conor-mac-aoidh** [prerender/prerender-node#79] opened 2015-07-20 13:26 UTC
Hi,

As far as I can tell, compatibiliy for HTTPS-only websites was broken in this commit:

https://github.com/prerender/prerender-node/commit/2a58a7cd15e38dee0b4b2064cb74dfef294b7a31#diff-168726dbe96b3ce427e7fedce31bb0bcL203

In my case, restoring the line:

```
var protocol = req.protocol;
```

Fixed my issue. Without this line, pre-render was fetching the cached version of the HTTP index - which redirects to the HTTPS index, resulting in javascript/not rendered content being delivered.

Conor

**Comment by thoop** [comment] 2015-07-20 14:58
Ah, thanks for that. Looking into this now.

**Comment by thoop** [comment] 2015-07-20 16:02
Can you try prerender-node 2.0.1? The issue should be fixed now. The problem is since we are moving away from an explicit express dependency, req.protocol might not exist. Should be fixed now that we're using `req.connection.encrypted`.

Thanks for that!

**Comment by thoop** [comment] 2015-07-24 04:59
@conor-mac-aoidh sorry to bug you. Any chance you were able to re-try this with the fixed version in v2.0.1? Thanks!

**Comment by conor-mac-aoidh** [comment] 2015-07-31 15:31
Yes that seems to have done the trick! Thanks

**Comment by thoop** [comment] 2015-07-31 15:40
Thanks for double checking!

**Closed by thoop** 2015-07-31 15:40 UTC
